### ISSUE TITLE
文件范围限制

### ISSUE THREAD

**Issue by cyang812** [qwertyuiop6/mm131#1]
请问 2500-4400， 以及 limit=65 是怎么确定的？

**Comment by qwertyuiop6** [comment]
你去仔细观察mm131的图片url,2500是性感区妹子编号的大概起始位置,4400为他们网站前两天最新更新到的位置。
65是每个妹子一套图片最多基本不会超过的数量大小

所以本质上，这并不是一个严谨意义的爬虫,而是我总结过规律之后的一个直接伪装浏览器请求的批量下载器
省去了解析页面的消耗。

这些我没有细说，提供了一个小白一站式操作,运行就下载了，你可以自己修改一下逻辑
