### ISSUE TITLE
headers里面的字典怎么获取啊

### ISSUE THREAD

**Issue by kissblack** [qwertyuiop6/mm131#10]
大佬，headers里面的字典是怎么获取的  f12吗  那f12又要找哪些呢？小弟我刚来github ，都还不太会用，多多关照哈。还有啊，大佬你是怎么把那么多py文件分开啊 。小弟我也写过1131的爬虫，但是我都写到一个py里面，求教怎么写多个py文件还能一起运行啊

**Comment by qwertyuiop6** [comment]
https://docs.python.org/zh-cn/3.8/tutorial/modules.html
